<TextWidget>:
    image: image

    BoxLayout:
        orientation: 'vertical'
        size: root.size

        BoxLayout:
            size_hint_y: 0.2
            Label:
                size_hint_x: 0.25
                id: carcass_order
                font_size: 30
                text: root.carcass_order
            Label:
                size_hint_x: 0.25
                id: body_number
                font_size: 30
                text: root.body_number
            Label:
                size_hint_x: 0
                id: barcode
                font_size: 0.0
                text: root.barcode
            Label:
                size_hint_x: 0
                id: filepath
                font_size: 0
                text: root.filepath

            Button:
                size_hint_x: 0.20
                id: sansyo_button
                text: 'csv'
                font_size: 68
                on_press: root.sansyoClicked()

            TextInput:
                size_hint_x: 0
                id: barcode_input
                focus: False
                font_size: 10
                multiline: False
                on_text_validate: root.barcodeDetected(self.text)
            TextInput:
                size_hint_x: 0
                id: barcode_input_sub
                focus: False
                font_size: 10
                multiline: False
                on_text_validate: root.barcodeDetectedSub(self.text)

        Image:
            size_hint_y: 1
            id: image
            source:root.image_src

        BoxLayout:
            size_hint_y: 0.2
            Button:
                id: ok
                text: "OK"
                font_size: 68
                on_release: root.okClicked()
            Button:
                id: cancel
                text: "Cancel"
                font_size: 68
                on_release: root.cancelClicked() 
            
<LoadDialog>:
    BoxLayout:
        size: root.size
        pos: root.pos
        orientation: "vertical"
        FileChooserIconView:
            id: filechooser
 
        BoxLayout:
            size_hint_y: None
            height: 30
            Button:
                text: "Cancel"
                on_release: root.cancel()
 
            Button:
                text: "Load"
                on_release: root.load(filechooser.path, filechooser.selection)
